### ISSUE TITLE
Cryptic error message when ffmpeg (or any command) is not found

### ISSUE THREAD

**Issue by Soren-Nordstrom** [mmilata/ektobot#16]
2015-01-17 11:40:48 INFO    root     ektobot started
2015-01-17 11:40:48 INFO    video    Using image Soren_Nordstrom_-_Protogenesis/folder.jpg as a cover
2015-01-17 11:40:48 INFO    video    Converting 01 - Soren Nordstrom - Critical Density.mp3
2015-01-17 11:40:48 ERROR   video    Converting Soren_Nordstrom_-_Protogenesis/01 - Soren Nordstrom - Critical Density.mp3 failed
2015-01-17 11:40:48 ERROR   root     Uncaught exception
Traceback (most recent call last):
  File "/home/nordstrom/Snakepit/ektobot/local/lib/python2.7/site-packages/ektobot-0.1-py2.7.egg/ektobot/command_line.py", line 153, in main
    videos(opts.dir, opts.dry_run, opts.outdir, opts.image, not opts.recode_audio)
  File "/home/nordstrom/Snakepit/ektobot/local/lib/python2.7/site-packages/ektobot-0.1-py2.7.egg/ektobot/video_convert.py", line 127, in videos
    run(cmdline)
  File "/home/nordstrom/Snakepit/ektobot/local/lib/python2.7/site-packages/ektobot-0.1-py2.7.egg/ektobot/utils.py", line 102, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2015-01-17 11:40:48 INFO    root     ektobot terminating

**Comment by mmilata** [comment]
It looks like you don't have `ffmpeg` installed?

**Comment by Soren-Nordstrom** [comment]
Dear God, you're right.  I just built a new server and I was 100% sure ffmpeg was installed with my initial install script, but it looks like Debian removed the ffmpeg package in favour of libav and I totally missed that error.  Thanks for pointing out the obvious!

**Comment by Soren-Nordstrom** [comment]
I should have spotted this when the dry run (which doesn't call ffmpeg) came back good. :p

**Comment by mmilata** [comment]
No problem:) I'll rename the issue to fix the error reporting.
